# Generated by Django 5.1 on 2024-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="manufactured_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
